- name: A bunch of aliasses I like to include
  copy: src="{{playbook_dir}}/files/bash_aliases" dest="{{install_dir}}/.bash_aliases"
  become: true
  become_user: tb170112 

- name: Change bash PS1 promt colour etc
  copy: src="{{playbook_dir}}/files/bash_profile" dest="{{install_dir}}/.bash_profile
  become: true
  become_user: tb170112 
